def find_motif(string, sub_string):

    positions = []
    for pos in range(len(string)):
        if string[pos:pos + len(sub_string)] == sub_string:
            positions.append(pos+1)
        
    return positions

res = find_motif('TTCGTTGAACGTTGAAACACGTTGAAGCAGCCCAGTGACGTCCCGTTGAACGTTGAAGGTAAAGCGTTGAAACTGACGTTGAACGTTGAAACGTTGAATCGTTGAAACGTTGAAACAAGCGGCTACGTTGAACGTTGAAGCTAGACGTTGAAACGTTGAATGCGTTGAATCGTTGAACGCGTTGAATCCGTTGAAAGGCTCGTTGAAATGCCCGTTGAAACGTTGAAGACGTTGAACGTTGAACGTTGAACCCCGTTGAACTCGTTGAAACTATTCCGTTGAACGTTGAATCGTTGAACACAGACGTTGAACTCCGTTGAACTGATTATAACGATAACGTTGAAGCCGTTGAAGCGTTGAAGCGTTGAACGTTGAAAGTACGTTGAAAAGACCGTTGAAGCGTTGAACGTTGAACGTTGAAGTCCCGTTGAAGGCGTTGAAATGACTCGTTGAAGCCGTTGAAGACTGCCGTTGAAACGTTGAAGCGTTGAAACCAGCAAAAACCAAGAGCCCGTTGAACGTTGAAAAGCGTTGAACACGCGTTGAACAATCGTTGAACGTTGAATCCTCAAGGTGGCGTTGAACCCCGTTGAAACGTTGAACGTTGAACGTTGAACCGTTGAATCGTTGAACAGCGTTGAACCAGAAGGCCGTTGAACAATATAGAATCCGTTGAATCTCGTTGAACGTTGAAGCGCCGTTGAACGCGTTGAAAATACCCCCGTTGAACTCTGAGGCGTTGAATCGTTGAACGTTGAATGCATCTGCGTTGAAGCGTTGAACGTTGAACGTTGAACGTTGAACCGTTGAAGTCCGTTGAACTCCCCTGACTCGTTGAACCGTTGAACGTTGAAGTGCGTTGAAGTGTACCCGTTGAACCGTTGAACGTTGAATGCTGACTCGTTGAATCGTTGAAACGCGTTGAAGGACCGTTGAAGACCGTTGAATAGTCGTTGAAATAC',
                 'CGTTGAACG')
for item in res:
    print(item, end = " ")